server:
  port: ${SERVER_PORT:9000}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
  h2:
    console:
      enabled: ${ENABLE_H2_CONSOLE:true}
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active: "default"
  jpa:
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}


build:
  version: ${BULD_VERSION:3.0.0}

cards:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "Cr1stal423 - Developer"
    email: "tutor@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
