server:
  port: ${SERVER_PORT:8090}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DRIVE_CLASS_NAME:org.h2.Driver}
  h2:
    console:
      enabled: ${ENABLE_H2_CONSOLE:true}
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active: "default"
  jpa:
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}


build:
  version: ${BULD_VERSION:3.0.0}

loans:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "Cr1stal423 - Developer"
    email: "tutor@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
