spring:
  config:
    activate:
      on-profile: "prod"


build:
  version: "1.0"


loans:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Cr1stal4231 - QA Lead"
    email: "tutor@eazybank.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345
