server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: ${APPLICATION_NAME:loans}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3309/loansdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}   
    password: ${SPRING_DATASOURCE_PASSWORD:Sqlwer}
  profiles:
    active: "prod"
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}

  sql:
    init:
      mode: always
  config:
    import: ${CONFIG_IMPORT:optional:configserver:http://localhost:8071/}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: "*"
