spring:
  application:
    name: ${APPLICATION_NAME:accounts}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/accountsdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Sqlwer}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
  sql:
    init:
      mode: always
  profiles:
    active: "prod"
  config:
    import: ${CONFIG_IMPORT:optional:configserver:http://localhost:8071/}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka
info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Microservice"
    version: "1.0.0"
logging:
  level:
    com:
      cr1stal423:
        accounts: DEBUG

