spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    driverClassName: ${DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
  jpa:
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
  hibernate:
    ddl-auto: ${HIBERNATE_DDL_AUTO:update}
server:
  port: ${SERVER_PORT:8080}